---
- hosts: all
  roles:
    - common
- hosts: rpk-kjhub-p02
  roles:
    - hub
  environment:
    KOJI_MASTER_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"
- hosts: rpk-kjbdr-p21
  roles:
    - builder
  environment:
      KOJI_SLAVE_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"

- hosts: rpk-kjbdr-p22
  roles:
    - builder
  environment:
      KOJI_SLAVE_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"

- hosts: rpk-kjhub-p03
  roles:
    - hub
  environment:
    KOJI_MASTER_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"

- hosts: rpk-kjbdr-p31
  roles:
    - builder
  environment:
      KOJI_SLAVE_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"

- hosts: rpk-kjbdr-p32
  roles:
    - builder
  environment:
      KOJI_SLAVE_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"
