---
- hosts: all
  roles:
    - common
- hosts: rpk-kjhub-p01
  roles:
    - hub
  environment:
    KOJI_MASTER_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"
- hosts: rpk-kjbdr-p11
  roles:
    - builder
  environment:
      KOJI_SLAVE_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"

- hosts: rpk-kjbdr-p12
  roles:
    - builder
  environment:
      KOJI_SLAVE_FQDN: "{{ hostvars[inventory_hostname]['fqdn'] }}"
